### ISSUE TITLE
Unable to Add Authentication to Signup/Login Page and Display Username on New Page

### ISSUE THREAD

**Issue by Dhruv07Maurya** [Dhruv07Maurya/rentwize-version-01#1]
I am experiencing difficulties adding authentication to the signup/login page of my application. After attempting to implement authentication, no HTML pages are being displayed. Additionally, I am unable to show the logged-in user's name on a new page, such as "Hello, newUser@".

Steps to Reproduce:

Attempt to add authentication to the signup/login page.
Notice that no HTML pages are displayed after this change.
Try to display the logged-in user's name on a new page, but it does not appear.
Expected Behavior: After successfully adding authentication, HTML pages should be displayed as intended, and the logged-in user's name should be shown on a new page, for example, "Hello, newUser@".

Actual Behavior: No HTML pages are displayed after attempting to add authentication, and the logged-in user's name is not shown on any new page.

Any assistance in resolving this issue would be greatly appreciated.

**Comment by Raghav-Mundhara** [comment]
Please assign this issue  to me!
